version: "v1"
sentinel:
  app:
    name: user
    type: 0
  log:
    dir: "/root/mygo/jam3/logs/csp"
    pid: false
    metric:
      maxFileCount: 14
      flushIntervalSec: 1
  stat:
    system:
      collectIntervalMs: 1000
