apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    app: search-service
spec:
  replicas: 1
  template:
    metadata:
      name: search-service
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: xbinwar3/search:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: search-service

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    app: search-service
    service: search-service
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 81
    name: http
  selector:
    app: search-service

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-host-bar
spec:
  ingressClassName: nginx
  rules:
  - host: "micro.test.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: search-service
            port:
              number: 81

