server:
  name: "project-search"
  addr: ":81"

zap:
  DebugFileName: "/root/mygo/jam3/logs/debug.log"
  InfoFileName:  "/root/mygo/jam3/logs/info.log"
  WarnFileName:  "/root/mygo/jam3/logs/error.log"
  MaxSize:       500
  MaxAge:        28
  MaxBackups:    3
db:
  dsn: root:123123@tcp(192.168.3.116:3306)/jam3?charset=utf8mb4&parseTime=True&loc=Local
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

grpc:
  addr: "127.0.0.1:8881"
  name: "search"
  version: "1.0.0"
  weight: 2

etcd:
  addrs:
    - "192.168.3.116:2379"

es:
  addr: "http://192.168.3.116:9200"
